### PR TITLE
Migrates argument parsing to argparse

### PR DESCRIPTION
**Pull request by resamsel**
Migrates to argparse, which allows easy addition of options. New options are min/max tag (positional arguments), --init, and --exclude-head (excludes HEAD from the list of tags). A full list of options can be shown when invoking the command with -h/--help.

### CODE REVIEW

**Comment by vaab** [comment]
Wow, many thanks for your interest and this PR. I've read it, I still need to test it.

I must warn you that I don't really like ``argparse`` (I feel it is very clumsy and limited compared to ``docopt`` or ``click`` for instance) but I recognize that it is broadly used and in python base libs (which has the great merit of no added dependencies). So in the end, for a few options, why not.

Your commit contains several different concerns. The introduction to go with ``argparse`` is one. The introduction of ``min/max`` tag and ``exclude-head`` is another. I mean that I might consider one of these concerns as a good idea and not the other. This generally helps for the whole process.

At last, I like to have each commit passing the tests (this helps for bisecting, or simply keeping things that goes together, staying together). One concern at a time. So I'll probably merge the second commit lines with the first one (and separate both)

We have also a minor API break (on the init argument that changes from positional to optional.)

Now for the code itself::
- you seem to make the assumption that LooseVersion from ``distutils`` has the same behavior than what ``git`` would have done for instance with ``git tag -l --sort=v:refname``.
    - why not use git refs ? this would allow the use of tags or more, remove the need or the ``exclude-head`` options, and you could give all this to ``git log`` directly without having to parse and filter anything. 
- there are no tests nor docs. (well, wait before writing them is okay for me if this PR is not sure to be pulled).

I think it is a great idea to introduce command line arguments that would permit to generate part of a changelog (and this min/max thing is exactly that). This would tackle part of #26 . So I'm all in for the underlying idea, but the implementation fall short for me on several points. Can you or are you willing to improve the point I mentionned ?

**Comment by resamsel** [comment]
Many thanks for looking into my pull request.

When I was skipping through your code I found this the place to add the desired filter. I used LooseVersion because the ```git tag``` command does not allow to use **git ref ranges**. If you can point me to a better suited place to add those filters I'd be happy to adapt my code. With those the --exclude-head parameter can be dropped as well, as you suggested.

I understand breaking the API through the use of the --init parameter is an issue. If you really need to keep it as a positional parameter I guess we would need to make the min/max tag optional arguments. Otherwise we would have problems deciding whether **init** is a command or it is a tag. Personally, I'd prefer the use of --init as an optional parameter, and make gitchangelog a new major release (3.0.0), but that's totally up to you.

Regarding tests and docs - I'll happily add them as soon as we agree on the change itself.

**Comment by vaab** [comment]
Sorry for the very late answer, your PR decided me to effectively make the move towards ``argparse``. I'll span again in your code to see the other good ideas and make choices perhaps tomorrow.

**Comment by vaab** [comment]
Ok, so, regarding the different feature that you brought, I have a candidate branch that:
- use ``argparse`` in a separate refactoring commit
  - that passes all the previous tests without changing the legacy command line.
  - introduce a ``show`` positional arguments, calling ``gitchangelog`` without arguments is a shortcut to call ``gitchangelog show``.
- A second commit introduce a REVLIST optional argument to ``gitchangelog``
  - new tests are added
  - doc is added
  - this provides the same functionnality than your ``--exclude-head`` and ``min_tag`` and ``max_tag``. For instance:
    - ``gitchangelog show 0.0.2..0.0.3`` would print changelog in between 0.0.2 and 0.0.3 (obviously excluding head).
    - calling ``gitchangelog show`` is equivalent to ``gitchangelog show HEAD``, so if you wish to exclude head, you can type ``gitchangelog show LASTTAG``. You obviously need to know here what is your last tag. So this is not completely equivalent. I might consider adding a optional argument that would roughly give you back this functionnality.

If you have any feedback/concerns, please let me know. I hope this answers your issues.

**Comment by resamsel** [comment]
Hi Valentin,

this is great, using the first positional argument as a command fixes the compatibility issues. The REVLIST argument to gitchangelog is exactly what I had in mind, but is much cleaner than what I proposed. No concerns regarding your changes.

Thanks for your time and effort, I appreciate it.

**Pull request closed without merging**
