### PR TITLE
Fixed execution in Windows (closes issue #6)

### PR DESCRIPTION
**Pull request by mikitex70**
Execution on Windows need some minor change in sub-process creation:
- close_fds must be False if redirection is used
- the command separator is '&' instead of ';'

### CODE REVIEW

**Comment by FlYnN91** [comment]
I tested these changes in my own fork and gitchangelog works great. tested on Windows 10, Python 2.7.

**Comment by vaab** [comment]
Ok, very nice. This will probably tackle #6. I'd like to add testing to all this (to prevent braking the windows version). Any experience on this matter ? (appveyor anyone ?).

**Comment by vaab** [comment]
I know that cookiecutter is a python project using appveyor. I'll integrate this myself when I'll find some time, although I may not have time these following weeks. Here's a good starting point if some of you are interested and have some spare time: https://github.com/audreyr/cookiecutter/blob/master/appveyor.yml

**Comment by vaab** [comment]
I'm finally having time to tackle this and move forward, gathering the 3 PR about this topic in a 4th proposition #68 with a very initial minimal automated test on windows.
As I borrowed from your PR, I'm using the ``Co-Authored-By`` tag, and added the feature request #69 so that gets implemented soon.
I'm closing this PR as I'd like to gather all comment around this first window support in #68 .
Many thanks for your PR that helped a lot, and feel free to comment my proposition. I'd like to push this as soon as possible and would be grateful if you had time to have a look at it.

**Pull request closed without merging**
