### PR TITLE
Improved packaging and distribution

### PR DESCRIPTION
**Pull request by tuukkamustonen**
As discussed in #34, suggesting following changes:
- Project now contains `gitchangelog` package, that contains deliverables
- Now using plain `package_data` to get templates next to code
- Binary was moved to scripts directory to avoid naming clash
- Minor tuning to MANIFEST.in

### CODE REVIEW

**Comment by vaab** [comment]
Sorry, I'm taking my time on this one because still undecided to make this move to having a ``gitchangelog`` package, and because all this will need thourough testing on various plateforms (I mean combinations of pip/setuptools). Probably these will need to be integrated in travis tests also in some ways.

**Comment by tuukkamustonen** [comment]
@vaab I am still using `gitchangelog` occasionally and would like #41 to get fixed. I can rebase and re-work this if you're open to moving stuff under `gitchangelog` package. It's not absolutely necessary to use `gitchangelog` package, but that allows putting the `templates` inside it and not placing them on the `site-packages` root (what if some other library places similarly named directory there?). What is your concern on using a package here? It's just a directory, more or less, and never visible to the user of the library.

I would also like to give up all the custom `autogen.sh` and `d2to1` stuff. I know it sounds a lot, but you don't see those in any(?) other open-source python project, and add complexity to the build.

**Comment by vaab** [comment]
@tuukkamustonen sorry for the (very) late answer on this topic. After fighting for the nth time against X major flaws in the ever moving target of python packaging, I've decided to move forward and switch ``gitchangelog`` from a single-file package to a full fledged package, as you suggested, a long time ago.

Some difference between your code and what I'm actually experiencing with:
- I prefer the ``src/`` layout, and this seems supported by python packagings for now. So this means
  I'm using ``src/gitchangelog`` as the base for all the files.
- I'm using ``MANIFEST.in`` + ``include_package_data = True`` that seems to be pushed by many 
  documentation as the best solution instead of using ``package_data``. And this has the advantage 
  that I don't need to repeat myself by listing files in ``setup.cfg``.

In addition, I somewhat simplified the ``.travis.yml`` to remove all the distribution tests, only because I managed to build a quick tool that gets all combinations of installation and will tests these distribution files.

I wouldn't be surprise that another buggy combination is still sitting out there waiting to bite the packaging. I hopefully will be able to add it to my distribution test matrix.

The commits are still not in master nor released (but they should appear in this thread after this message), as I want to take a look at other issues before releasing something like ``3.0``.

**Comment by tuukkamustonen** [comment]
Hi, that's good to hear :) I might have different opinion on some of the details, but as long as the packaging gets fixed and simplified, I'm happy.

Would you mind doing a PR once you are willing to merge the changes so we can discuss those details?

**Comment by vaab** [comment]
You'll find the PR on #67

**Pull request closed without merging**
