### PR TITLE
Match ignore_regexps against whole commit msg

### LINKED ISSUE #115: ignore_regexps doesnt match against whole message, only subject
Documentation in the reference config file says this:

```
## Any commit having its full commit message matching any regexp listed here
## will be ignored and won't be reported in the changelog.
```

However: https://github.com/vaab/gitchangelog/blob/master/src/gitchangelog/gitchangelog.py#L1592

Looks like that the ignored regexps are only matched against commit.subject.

Personally i prefere to keep the commit subject line under 72 characters and thus, sometimes im forced to put, say, !minor into the first actual line of the commit message (or just last). And then, these lines will show up in the changelog.

### PR DESCRIPTION
**Pull request by rasjani**
Fixes #115

### CODE REVIEW

**Comment by rasjani** [comment]
CI failure in Appveyor is not due to my changes: https://ci.appveyor.com/project/vaab/gitchangelog/builds/24199864/job/oc0rrqmycsvsi7k2

**Review by yellowsoar — COMMENTED** [review]
Since `commit.subject` and `commit.body` are both str, it might be lighter and faster by using plus?

```
for commit in commits:
    if any(re.search(pattern, commit.subject + commit.body) is not None
           for pattern in ignore_regexps):
        continue
```

**Comment by rasjani** [comment]
No preference either way, rationale for using str formatting was only to also have linebreak between subject & body because i wasnt sure if the \n would be in there  and there might be search pattern that would match if two strings are just appended together  and explicitly opted out of doing subject + linefeed + body style approach for readability .. 

But true, + is most likely faster.

**Comment by Viatorus** [comment]
Why is this closed?

**Pull request closed without merging**
